// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11.09.2025, 02:50:47
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/dym-kz/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/dym-kz/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/dym-kz/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/dym-kz/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/dym-kz/plugins/**/*.{js,ts,mjs}","C:/dym-kz/composables/**/*.{js,ts,mjs}","C:/dym-kz/utils/**/*.{js,ts,mjs}","C:/dym-kz/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/dym-kz/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/dym-kz/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/dym-kz/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;